config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :major_systems
    resources :pegs
  end

  namespace :public do
    resources :major_systems, only: [:index, :show]
    resource :homepage, only: :show
  end

  devise_for :brains
  namespace :brain do
    resources :major_systems, only: [:index, :show, :destroy]
    resources :pegs, only: [:edit, :update]
    resources :conversions, only: [:new, :create]
  end

  root "public/homepages#show"
end

app/models/peg.rb
class Peg < ApplicationRecord
  belongs_to :major_system, foreign_key: "mnemonic_system_id"

  has_one_attached :image, dependent: :destroy

  validates :number, presence: false, numericality: { only_integer: true }
  validates :phrase, presence: false

  # TODO: This might break once pegs with numbering like `01`, `001`, etc. are
  # introduced.
  scope :ordered, -> { order('number::integer ASC') }
end

app/controllers/admin/pegs_controller.rb
# The super admin part of the application.
class Admin::PegsController < ApplicationController
  http_basic_authenticate_with(
    name: Rails.application.credentials.dig(:basic_auth_username),
    password: Rails.application.credentials.dig(:basic_auth_password)
  )

  before_action :set_peg, only: %i[ show edit update destroy ]

  # GET /pegs
  def index
    # TODO: The sorting will break with 0-prepended pegs like "00", "01", etc.
    if !filter_params[:set_id]
      # FIXME: Only showing German ones as default, while other admins work on it.
      # 43 seems like magic 42 but actually stands for Stenger's peg set.
      # @pegs = Peg.all.ordered
      @pegs = Peg.where(mnemonic_system_id: 43).ordered
    else
      @pegs = Peg.where(mnemonic_system_id: filter_params[:set_id]).ordered
    end
  end

  # GET /pegs/1
  def show
  end

  # GET /pegs/new
  def new
    @peg = Peg.new
  end

  # GET /pegs/1/edit
  def edit
  end

  # POST /pegs
  def create
    @peg = Peg.new(peg_params)

    if @peg.save
      redirect_to admin_peg_url(@peg), notice: "Peg was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /pegs/1
  def update
    if @peg.update(peg_params)
      redirect_to admin_peg_url(@peg), notice: "Peg was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /pegs/1
  def destroy
    @peg.destroy

    redirect_to admin_pegs_url, notice: "Peg was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peg
      @peg = Peg.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def peg_params
      params.require(:peg).permit(:image, :number, :phrase, :mnemonic_system_id)
    end

    def filter_params
      params.permit(:set_id)
    end
end

app/controllers/brain/pegs_controller.rb
class Brain::PegsController < ApplicationController
  def edit
    @peg = Peg.find(params[:id])
  end

  def update
    peg = Peg.find(params[:id])

    if peg.update(peg_params)
      redirect_to edit_brain_peg_path(peg), notice: "Your peg was successfully updated"
    else
      flash.now[:alert] = "Something went wrong"
    end
  end

  private

  def peg_params
    params.require(:peg).permit(:number, :phrase)
  end
end

app/controllers/pegs_controller.rb
# The super admin part of the application.
# TODO: Move to Admin:: namespace.
class PegsController < ApplicationController
  http_basic_authenticate_with(
    name: Rails.application.credentials.dig(:basic_auth_username),
    password: Rails.application.credentials.dig(:basic_auth_password)
  )

  before_action :set_peg, only: %i[ show edit update destroy ]

  # GET /pegs
  def index
    # TODO: The sorting will break with 0-prepended pegs like "00", "01", etc.
    @pegs = Peg.all.sort_by {|peg| peg.number.to_i}
  end

  # GET /pegs/1
  def show
  end

  # GET /pegs/new
  def new
    @peg = Peg.new
  end

  # GET /pegs/1/edit
  def edit
  end

  # POST /pegs
  def create
    @peg = Peg.new(peg_params)

    if @peg.save
      redirect_to peg_url(@peg), notice: "Peg was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /pegs/1
  def update
    if @peg.update(peg_params)
      redirect_to peg_url(@peg), notice: "Peg was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /pegs/1
  def destroy
    @peg.destroy

    redirect_to pegs_url, notice: "Peg was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peg
      @peg = Peg.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def peg_params
      params.require(:peg).permit(:image, :number, :phrase, :mnemonic_system_id)
    end
end

app/views/pegs/_form.html.erb
<%= form_with(model: peg, class: "contents") do |form| %>
  <% if peg.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(peg.errors.count, "error") %> prohibited this peg from being saved:</h2>

      <ul>
        <% peg.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :number %>
    <%= form.text_field :number, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :phrase %>
    <%= form.text_field :phrase, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :mnemonic_system_id, "Mnemonic system ID" %>
    <%= form.text_field :mnemonic_system_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/pegs/_peg.html.erb
<div id="<%= dom_id peg %>" class="mt-28">

  <p class="my-5 text-center font-mono text-4xl">
    <%= peg.number %>
  </p>

  <p class="my-5 text-center font-mono text-4xl">
    <%= peg.phrase %>
  </p>

  <p class="hero container max-w-screen-lg mx-auto pb-10 flex justify-center">
    <% if peg.image.attached? %>
      <%= link_to image_tag(peg.image.variant(resize_to_limit: [200, 200]), class: "peg-image"), peg_path(peg) %>
    <% end %>
  </p>

  <% if action_name != "show" %>
    <div class="text-center">
      <%= link_to "Show this peg", peg, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to 'Edit this peg', edit_peg_path(peg), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100
           inline-block font-medium" %>
      <hr class="mt-6">
    </div>
  <% end %>
</div>

app/views/pegs/index.html.erb
<div class="w-full relative">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="text-center">
    <h1 class="font-bold text-4xl">Mnemonic Pegs</h1>
  </div>

  <div id="quick-links" class="grid grid-cols-10 gap-1 text-center mt-28">
    <% @pegs.each do |peg| %>
      <%= link_to peg.number, peg_path(peg), class: "text-blue-600 underline" %>
    <% end %>
  </div>

  <div id="pegs">
    <%= render @pegs %>
  </div>

  <%= link_to 'New Peg', new_peg_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium fixed bottom-14 right-14" %>
</div>

app/views/pegs/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New peg</h1>

  <%= render "form", peg: @peg %>

  <%= link_to 'Back to pegs', pegs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>