config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :major_systems
    resources :pegs
  end

  namespace :public do
    resources :major_systems, only: [:index, :show]
    resource :homepage, only: :show
  end

  devise_for :brains
  namespace :brain do
    resources :major_systems, only: [:index, :show, :destroy]
    resources :pegs, only: [:edit, :update]
    resources :conversions, only: [:new, :create]
  end

  root "public/homepages#show"
end

app/models/major_system.rb
class MajorSystem < MnemonicSystem
  DEFAULT_LANGUAGE_ISO = "en"

  belongs_to :brain, optional: true
  has_many :pegs, foreign_key: "mnemonic_system_id", dependent: :destroy

  # TODO: origin should be an additional resource:
  # Origin.author, Origin.url, Origin.title, etc.
  validates :origin, presence: true
  validates :origin_url, format: URI::DEFAULT_PARSER.make_regexp(%w[http https])

  validates :language_iso, presence: true, length: {maximum: 2, minimum: 2}

  scope :original, -> { where(brain: nil) }
  scope :english, -> { where(language_iso: "en") }
  scope :language, ->(language_iso) do
    where(language_iso: language_iso.presence || DEFAULT_LANGUAGE_ISO)
  end
end

app/controllers/admin/major_systems_controller.rb
# The super admin part of the application.
class Admin::MajorSystemsController < ApplicationController
  http_basic_authenticate_with(
    name: Rails.application.credentials.dig(:basic_auth_username),
    password: Rails.application.credentials.dig(:basic_auth_password)
  )

  before_action :set_major_system, only: %i[ show edit update destroy ]

  # GET /major_systems
  def index
    @major_systems = MajorSystem.all
  end

  # GET /major_systems/1
  def show
  end

  # GET /major_systems/new
  def new
    @major_system = MajorSystem.new
  end

  # GET /major_systems/1/edit
  def edit
  end

  # POST /major_systems
  def create
    @major_system = MajorSystem.new(major_system_params)

    if @major_system.save
      redirect_to admin_major_system_path(@major_system), notice: "Major system was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /major_systems/1
  def update
    if @major_system.update(major_system_params)
      redirect_to admin_major_system_path(@major_system), notice: "Major system was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /major_systems/1
  def destroy
    @major_system.destroy
    redirect_to admin_major_systems_url, notice: "Major system was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_major_system
      @major_system = MajorSystem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def major_system_params
      params.require(:major_system).permit(
        :origin,
        :origin_url,
        :language_iso,
        :brain_id
      )
    end
end

app/controllers/brain/major_systems_controller.rb
class Brain::MajorSystemsController < ApplicationController
  before_action :authenticate_brain!

  def index
    @major_systems = current_brain.major_systems
  end

  def show
    @major_system = current_brain.major_systems.find(major_system_params)
  end

  def update
    @major_system = current_brain.major_systems.find(major_system_params)
  end

  def destroy
    @major_system = current_brain.major_systems.find(major_system_params)

    if @major_system.destroy
      redirect_to brain_major_systems_path, notice: "Successfully forgotten"
    else
      flash[:alert] = "There was an error removing this system from your brain"
      render :show
    end
  end

  private

  def major_system_params
    params.require(:id)
  end
end

app/controllers/major_systems_controller.rb
# The super admin part of the application.
# TODO: Move to Admin:: namespace.
class MajorSystemsController < ApplicationController
  http_basic_authenticate_with(
    name: Rails.application.credentials.dig(:basic_auth_username),
    password: Rails.application.credentials.dig(:basic_auth_password)
  )

  before_action :set_major_system, only: %i[ show edit update destroy ]

  # GET /major_systems
  def index
    @major_systems = MajorSystem.all
  end

  # GET /major_systems/1
  def show
  end

  # GET /major_systems/new
  def new
    @major_system = MajorSystem.new
  end

  # GET /major_systems/1/edit
  def edit
  end

  # POST /major_systems
  def create
    @major_system = MajorSystem.new(major_system_params)

    if @major_system.save
      redirect_to @major_system, notice: "Major system was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /major_systems/1
  def update
    if @major_system.update(major_system_params)
      redirect_to @major_system, notice: "Major system was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /major_systems/1
  def destroy
    @major_system.destroy
    redirect_to major_systems_url, notice: "Major system was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_major_system
      @major_system = MajorSystem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def major_system_params
      params.require(:major_system).permit(
        :origin,
        :origin_url,
        :language_iso,
        :brain_id
      )
    end
end

app/views/admin/major_systems/_form.html.erb
<%= form_with(model: major_system, url: admin_major_system_form_path, class: "contents") do |form| %>
  <% if major_system.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(major_system.errors.count, "error") %> prohibited this major_system from being saved:</h2>

      <ul>
        <% major_system.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :origin %>
    <%= form.text_field :origin, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :origin_url, "Origin URL" %>
    <%= form.text_field :origin_url, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :language_iso %>
    <%= form.text_field :language_iso, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :brain_id %>
    <%= form.text_field :brain_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/major_systems/_major_system.html.erb
<div id="<%= dom_id major_system %>">
  <p class="my-5">
    <strong>ID:</strong> <%= major_system.id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Origin:</strong>
    <%= major_system.origin %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Origin URL:</strong>
    <%= major_system.origin_url %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Language iso:</strong>
    <%= major_system.language_iso %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Brain:</strong>
    <%= major_system.brain_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this major system", admin_major_system_path(major_system), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this major system", edit_admin_major_system_path(major_system), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/admin/major_systems/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing major system</h1>

  <%= render "form", major_system: @major_system %>

  <%= link_to "Show this major system", admin_major_system_path(@major_system), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to major systems", admin_major_systems_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/major_systems/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Major systems</h1>
    <%= link_to 'New major system', new_admin_major_system_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="major_systems" class="min-w-full">
    <%= render partial: "admin/major_systems/major_system", collection: @major_systems %>
  </div>
</div>

app/views/admin/major_systems/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New major system</h1>

  <%= render "form", major_system: @major_system %>

  <%= link_to 'Back to major systems', admin_major_systems_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/major_systems/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @major_system %>

    <%= link_to 'Edit this major system', edit_admin_major_system_path(@major_system), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this major system', admin_major_system_path(@major_system), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to major_systems', admin_major_systems_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>