config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :major_systems
    resources :pegs
  end

  namespace :public do
    resources :major_systems, only: [:index, :show]
    resource :homepage, only: :show
  end

  devise_for :brains
  namespace :brain do
    resources :major_systems, only: [:index, :show, :destroy]
    resources :pegs, only: [:edit, :update]
    resources :conversions, only: [:new, :create]
  end

  root "public/homepages#show"
end

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar sticky-top" style="background-color: white;">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
        <%= image_tag("favicon.png", alt: "Logo", width: 30, height: 24, class: "d-inline-block align-text-top") %>
        memocortex
      </a>
      <% if brain_signed_in? %>
        <div>Hi <%= link_to(current_brain.email, brain_major_systems_path) %></div>
        <%= button_to "Disconnect 🧠💤", destroy_brain_session_path, method: :delete, class: "btn btn-primary" %>
      <% else %>
        <form class="d-flex">
          <%= link_to "Connect 🔌🧠", new_brain_session_path, class: "btn btn-outline-primary me-2" %>
          <%= link_to "Register ➕🧠", new_brain_registration_path, class: "btn btn-outline-secondary me-2" %>
        </form>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>memocortex</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path("favicon.png") %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <main class="container-fluid mt-5">

      <% if alert.present? %>
        <p class="alert alert-danger" role="alert"><%= alert %></p>
      <% end %>

      <% if notice.present? %>
        <p class="alert alert-primary" role="alert"><%= notice %></p>
      <% end %>

      <div class="row justify-content-center">
        <div class="col-8">
          <%= yield %>
        </div>
      </div>
    </main>
  </body>

  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <%= link_to "About ℹ️", public_homepage_path, class: "nav-link px-2 text-muted" %>
      <%= link_to "Major Systems 🔮", public_major_systems_path, class: "nav-link px-2 text-muted" %>
      <%= link_to "Connect 🧠🔌", brain_session_path, class: "nav-link px-2 text-muted" unless brain_signed_in? %>
    </ul>
    <p class="text-center text-muted">
      Made with 🧠 by <%= link_to "RichStoneIO", "https://richstone.io/train-your-developer-memory/", target: "_blank" %>
      © <%= Time.current.year %></p>
  </footer>
</html>